### ISSUE TITLE
There's no code in the repo.

### ISSUE THREAD

**Issue by mrwacky42** [deniszh/collectd-iostat-python#1]

**Comment by mre** [comment]
:dancers:

**Comment by ghost** [comment]
:+1:

**Comment by nisc-acooper** [comment]
repo so empty... any possibility that this script exists? Would love to use it in our environment!

**Comment by deniszh** [comment]
Wow, it seems demand is huge... OK, gimme couple of days to prepare code to
public.

22:40, вт, 17.02.2015, Andrew Cooper notifications@github.com:

**Comment by deniszh** [comment]
Here you are :)
