### ISSUE TITLE
Ceph RBD support

### ISSUE THREAD

**Issue by fiskn** [deniszh/collectd-iostat-python#18]
I would like to use this plugin to collect iostat stats from mapped Ceph RBD's. They normally just get mapped as /dev/rbd0, rbd1 rbd2.....etc Which considering the RBD's could be mapped in any order, means that overtime you will never know what stats are from what RBD.

However when you map a RBD is also creates a symlink in the format:

/dev/rbd/<pool_name>/<rbd_name>

You can retrieve this symlink from udev, so I'm hoping there might be a way to use pyudev to remap the name to the friendly symlink. Is this something you could advise on?

**Comment by deniszh** [comment]
Hi @fiskn,
Sorry, I have no experience with Ceph's RBD. You can use pyudev for getting device info, indeed - https://pyudev.readthedocs.io/en/latest/guide.html#enumerating-devices
Then you can match it with /dev/rbdX names and produce some sane metric name from it, looks plausible.

**Comment by fiskn** [comment]
Thanks for the pointer, DEVLINKS was the parameter I needed.
