### ISSUE TITLE
python/collectd compatibility

### ISSUE THREAD

**Issue by nisc-acooper** [deniszh/collectd-iostat-python#2]
I am curious if others are seeing this.  When attempting to use this plugin with collectd 5.4 and python 2.6.6 on Centos 6.5,  we see OSError: No child process on the Popen.communicate() call when trying to pull data back from iostat.  This appears to be related to overwriting the SIGCHLD signal handler, which appears to be what collectd is doing.  I am sure this is localized to environment somehow, I am just curious if anyone else is seeing what I am seeing?

This script works just fine at the command line (running the main function).  It only shows the symptoms when ran inside of collectd under the python plugin.

**Comment by deniszh** [comment]
I was testing it only on Ubuntu 12.04 / 14.04, sorry. And yes, I saw that error in original python-iostat module - https://bitbucket.org/jakamkon/python-iostat/src/f393ca1f3ca464c43aa19c9f6844197d3d3b01f7/iostat/iostat.py?at=default - which was using popen2.Popen3(), but it was gone after rewriting it in subprocess.Popen()
It looks similar to this bug - http://bugs.python.org/issue1731717. I'll try to wind up CentOS VM and try it there. It seems that bug description still contains couple of workarounds which I can try.

Thanks for report and patience :+1:

**Comment by deniszh** [comment]
Yes, I'm confirming this issue:

```
Mar  4 09:35:50 vagrant-centos65 collectd[3173]: collectd-iostat-python plugin [verbose]: Read callback called
Mar  4 09:35:52 vagrant-centos65 collectd[3173]: Unhandled python exception in read callback: OSError: [Errno 10] No child processes
Mar  4 09:35:52 vagrant-centos65 collectd[3173]: read-function of plugin `python.collectd_iostat_python' failed. Will suspend it for 20 seconds.
```

Will debug that today.

**Comment by deniszh** [comment]
@nisc-acooper,
Please check if my fix is working for you. Unfortunately it seems for python 2.6 it's only way how it can be fixed - but collect's exec plugin will be broken because of that... I'll explain in README if fix works for you.

**Comment by deniszh** [comment]
So, it seems that for python 2.6.6 (which is only option for RHEL/CentOS) this bug is still active - http://bugs.python.org/issue1731717 and only option how to fix that it's restore SIGCHLD signal handler, but according to collectd documentation it will break collectd exec plugin - https://collectd.org/documentation/manpages/collectd-python.5.shtml#configuration
Will add this info in README.

**Comment by nisc-acooper** [comment]
I can confim that this now works correctly for me.  Thanks for the effort put in to fix!
