### ISSUE TITLE
TypeError: Dataset requests_merged_per_second not found

### ISSUE THREAD

**Issue by marcin-github** [deniszh/collectd-iostat-python#8]
Hi!
I tried to launch collectd-iostat-python on kernel with set in kernel "SCSI_MQ_DEFAULT". The result is that no sechduler for bolck device is used:
# cat /sys/block/sda/queue/scheduler 
none

and collectd-iostat-python can't work on such configuration, it throws:
Unhandled python exception in read callback: `TypeError: Dataset requests_merged_per_second not found`

**Comment by deniszh** [comment]
Hi @marcin-github,
Could you please send me (maybe link to gist with) results of `iostat -kNd 1 2` and `iostat -kNdx 1 2` from your server?

Thanks!

**Comment by marcin-github** [comment]
For me it's not problem to make it public.
# iostat -kNd 1 2
Linux 4.1.12-gentoo (clx-db1)   05/24/2016      _x86_64_        (12 CPU)

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda              12.93        88.89        30.58 1241919812  427271402
sdb            1322.35      1403.23     13797.26 19604599843 192761939040
clx--db1--vg-swap     0.12         0.20         0.26    2861300    3635740
clx--db1--vg-tmp     0.00         0.00         0.00       6845      34276
clx--db1--vg-var     0.63         6.31         4.49   88117685   62751656
clx--db1--vg-mysql  1143.61        78.84     12862.92 1101464313 179708276120
clx--db1--vg-pgsql   197.20      1401.04       959.92 19573910790 13411047616
drbd1           196.17      1395.62       954.30 19498315066 13332606912
drbd0            19.12        55.15       113.68  770446622 1588215328

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda              15.00        64.00         0.00         64          0
sdb             916.00       452.00     10476.00        452      10476
clx--db1--vg-swap     0.00         0.00         0.00          0          0
clx--db1--vg-tmp     0.00         0.00         0.00          0          0
clx--db1--vg-var     0.00         0.00         0.00          0          0
clx--db1--vg-mysql   868.00         0.00     10476.00          0      10476
clx--db1--vg-pgsql    49.00       460.00         0.00        460          0
drbd1            49.00       460.00         0.00        460          0
drbd0             0.00         0.00         0.00          0          0

# iostat -kNdx 1 2
Linux 4.1.12-gentoo (clx-db1)   05/24/2016      _x86_64_        (12 CPU)

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.24    9.04    3.89    88.89    30.58    18.48     0.12    9.06    6.27   15.55   3.26   4.21
sdb               0.00     6.44   79.30 1243.05  1403.23 13797.26    22.99     0.04    0.03    2.33    0.13   0.19  25.51
clx--db1--vg-swap     0.00     0.00    0.05    0.07     0.20     0.26     8.00     0.00   20.24   14.42   24.82   1.86   0.02
clx--db1--vg-tmp     0.00     0.00    0.00    0.00     0.00     0.00     8.14     0.00    3.04    5.77    2.55   1.39   0.00
clx--db1--vg-var     0.00     0.00    0.11    0.52     6.31     4.49    34.40     0.00    7.83   24.72    4.34   0.75   0.05
clx--db1--vg-mysql     0.00     0.00    3.75 1139.86    78.84 12862.92    22.63     0.01    0.01    6.48    0.26   0.13  14.86
clx--db1--vg-pgsql     0.00     0.00   84.05  113.14  1401.03   959.92    23.95     0.29    1.48    2.65    0.60   1.24  24.38
drbd1             0.00     0.00   84.00  112.17  1395.62   954.30    23.96     0.28    1.45    2.66    0.55   1.25  24.55
drbd0             0.00     0.00    2.46   16.66    55.15   113.68    17.66     0.02    1.28    6.00    0.59   0.49   0.93

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00     0.00   57.00 1147.00   640.00 15812.00    27.33     1.90    1.58   15.44    0.89   0.64  77.00
clx--db1--vg-swap     0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
clx--db1--vg-tmp     0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
clx--db1--vg-var     0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
clx--db1--vg-mysql     0.00     0.00    0.00 1046.00     0.00 15408.00    29.46     1.02    0.98    0.00    0.98   0.52  54.00
clx--db1--vg-pgsql     0.00     0.00   57.00  100.00   640.00   400.00    13.25     0.89    5.67   15.44    0.10   3.50  55.00
drbd1             0.00     0.00   57.00  100.00   640.00   400.00    13.25     0.89    5.67   15.44    0.10   3.50  55.00
drbd0             0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

**Comment by deniszh** [comment]
Strange, looks good on first look. Let me dig that more.

**Comment by deniszh** [comment]
Hi @marcin-github ,

Very strange, indeed. I put your output as result of `iostat` run - it works fine  - https://gist.github.com/deniszh/431e916c786f630928b7a9f5f7a0a4fd

Hmmmm....Does error above happened during running by command line or running through `collectd`?

**Comment by marcin-github** [comment]
Hi Denis,
mentioned error appears only in daemon.log and is emiting by collectd. When I run plugin from cmdline, as user "collectd" it just works. Now I can say that it's strange. 
I'm not very familiar with collectd so next question may by silly: shouldn't be key "requests_merged_per_second" mentioned in iostat_types.db?

**Comment by deniszh** [comment]
Yes, it should. And it is - if you check iostat_types.db

**Comment by marcin-github** [comment]
I was blind and I didn't see "requests_merged_per_second" in iostat_types.db. But it makes me wonder why collectd didn't see this key?
Answer is simple, I didn't add line:
TypesDB "/path/to/collectd/iostat_types.db"
So it's my fault. I'm sorry for taking your time for this.

BTW when we talk, when I use configuration like below:

`TypesDB "/data/bin/collectd/iostat_types.db"`
`<Plugin python>`
`ModulePath "/data/bin/collectd/"`
`Import "collectd_iostat_python"`
`<Module collectd_iostat_python>`
 `Path "/usr/bin/iostat"`
 `Interval 2`
`Count 2`
`Verbose true`
`NiceNames true`
`PluginName collectd_iostat_python`
`</Module>`
`</Plugin>`

I'm getting only values "bytes-read","bytes-write" and "percent-util" in rrd files. In syslo I can see that plugin sends other data, ex.: 
`collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-clx--db1--vg-swap.avg_wait_time-write=0.0`

When I change `NiceNames` to `NiceNames false` then I'm getting detailed graphs.
Am I doing something wrong again?

Second question, on graph called "collectd_iostat_python bytes" I see that OS is writing avg 248M  bytes. But iostat shows that values are usually lower:
` iostat -kNd 20 2 /dev/sdb
Linux 4.1.12-gentoo (clx-db1)   06/01/2016      _x86_64_        (12 CPU)

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sdb            1313.20      1390.70     13773.62 20401750651 202060850260

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sdb            1183.10      1487.20     13655.00      29744     273100
`
Are this values correct?

**Comment by deniszh** [comment]
Hi @marcin-github 
1. Sorry, never used this plugin with RRD files. If debug output shows that - data should be in collectd. At least it works for Graphite reporting.
Nice names just rename metrics - instead rrqm_s you'll get requests_merged_per_second, should not affect metrics itself.
2. This plugin not doing anython magical. If you saying

```
Interval 2
Count 2
```

it will run `iostat -kNd 2 2` and `iostat -kNdx 2 2` and take last line of output as result.

**Comment by marcin-github** [comment]
Hmm, I'm still not sure about correctness. I turned on verbose mode. With "nicenames false" I'm getting:
`tail -f /var/log/daemon.log|grep collectd_iostat_python-sdb`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-wrqm_s=0.0`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-rrqm_s=0.0`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-await=1.34`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-svctm=0.6`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-kB_read=1388.0`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-avgrq_sz=23.02`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-w_await=0.44`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-avgqu_sz=1.73`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-r_s=78.5`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-kB_wrtn_s=14048.0`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-kB_read_s=694.0`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-rkB_s=694.0`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-w_s=1208.0`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-kB_wrtn=28096.0`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-wkB_s=14114.0`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-tps=1283.5`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-r_await=15.22`
`Jun  2 15:57:33 clx-db1 collectd[12733]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.gauge-_util=77.0`

Those looks ok.
Now with "NiceNames True":
`tail -f /var/log/daemon.log|grep collectd_iostat_python-sdb`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.requests_merged_per_second-write=0.0`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.requests_merged_per_second-read=0.0`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.avg_wait_time-=1.95`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.avg_service_time-=0.63`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.bytes-read=10960000.0`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.avg_request_size-=25.65`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.avg_wait_time-write=1.2`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.avg_request_queue-=2.3`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.per_second-read=60.0`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.bytes_per_second-write=145500000.0`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.bytes_per_second-read=5480000.0`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.bytes_per_second-read=5480000.0`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.per_second-write=1117.5`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.bytes-write=291000000.0`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.bytes_per_second-write=145560000.0`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.transfers_per_second-=1176.5`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.avg_wait_time-read=16.0`
`Jun  2 16:00:35 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.percent-util=74.0`

a) there is no word "gauge", is it ok?
b) all values with words "bytes" are very round, all values has 4 zeroes on the left on decimal dot
c) iostat shows different values, ex: 
# date && iostat -kNx 2 2 /dev/sdb  
Thu Jun  2 16:12:23 CEST 2016
Linux 4.1.12-gentoo (clx-db1)   06/02/2016      _x86_64_        (12 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.33    0.01    3.65    3.89    0.00   89.13

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00     6.38   79.13 1232.53  1387.41 13760.53    23.10     0.18    0.13    3.03    0.18   0.22  28.22

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           1.76    0.04    3.02    5.87    0.00   89.30

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00     0.00   56.50 1257.00   540.00 12150.00    19.32     1.84    1.40   14.25    0.82   0.49  64.50

ln log is:
Jun  2 16:12:25 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.bytes_per_second-write=121140000.0
Jun  2 16:12:25 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.bytes_per_second-read=5560000.0
Jun  2 16:12:25 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.bytes_per_second-read=5560000.0
Jun  2 16:12:25 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.per_second-write=1244.5
Jun  2 16:12:25 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.bytes-write=242280000.0
Jun  2 16:12:25 clx-db1 collectd[13260]: collectd_iostat_python plugin [verbose]: Sending value: collectd_iostat_python-sdb.bytes_per_second-write=121080000.0

BTW, iostat has "-k" "by default:
 iostat 1 1 /dev/sdb
Linux 4.1.12-gentoo (clx-db1)   06/02/2016      _x86_64_        (12 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.33    0.01    3.65    3.89    0.00   89.13

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sdb            1311.66      1387.40     13760.53 20494728863 203271420368

 iostat -k 1 1 /dev/sdb
Linux 4.1.12-gentoo (clx-db1)   06/02/2016      _x86_64_        (12 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.33    0.01    3.65    3.89    0.00   89.13

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sdb            1311.66      1387.40     13760.53 20494739819 203271642392

iostat -m 1 1 /dev/sdb
Linux 4.1.12-gentoo (clx-db1)   06/02/2016      _x86_64_        (12 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.33    0.01    3.65    3.89    0.00   89.13

Device:            tps    MB_read/s    MB_wrtn/s    MB_read    MB_wrtn
sdb            1311.66         1.35        13.44   20014399  198507555

**Comment by deniszh** [comment]
Hm, looks you're right, niceNames multiple results on 10000 instead of 1000, when calculating bytes from kBytes. I fixed that by changing coefficients. Please try now.
@jtyr - maybe you're also interested with that.

**Comment by jtyr** [comment]
Yeah, it looks like I did a typo when using the exponential format - instead of 1e3 I used 10e3 ;o)

**Comment by marcin-github** [comment]
Now it's muuch better! Thanks!
But there is still something weird, I didn't track what is the problem yet (and I'll back to the finding bug after a weekend). 
Values logged in syslog (using "verbose true" in plugin configuration) looks good. Then local collectd sends values to remote collectd which writes metrics to the local RRD files and proxies metrics to the remote InfluxDB. Both in RRD and in InfluxDB values are wrong. It looks that values wrote to databases are doubled.

**Comment by jtyr** [comment]
> a) there is no word "gauge", is it ok?

Yes, that's absolutely OK. `gauge` is a generic type used in Collectd when you don't create the type DB entry. Once you have the DB entry, you can use whatever name in place of the `gauge`.

**Comment by marcin-github** [comment]
I think I now what is going on but I don't know why.
Values in RRD file, which I'm looking on are bytes, not bytes per second. This is why I can see doubled values ("Interval 2"). 
Summary: I didn't load iostat_types.db in collectdb server and in influxdb - this explains whay I didn't saw values e.g. bytes_per_second. Plugin works as it should, I can't see any issue in it. 
Thanks!
